# Generated by Django 2.2.24 on 2021-08-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0017_remove_unique_from_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainaddress',
            name='block_list_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='relayaddress',
            name='block_list_emails',
            field=models.BooleanField(default=True),
        ),
    ]
